### ISSUE TITLE
Add basic installer.

### ISSUE THREAD

**Issue by jmervine** [MaxCDN/shml#10]
I'd like to add an installer modeled after the one used in [odb/shunt](https://github.com/odb/shunt). Not sure about the adding to path though, as this isn't technically an executable. If done, I'm thinking it could be sourced with:

```
source "$(which shml.sh)"
```

Feedback welcome.

**Comment by jdorfman** [comment]
Check gh-pages. I wrote a 1-liner installer

**Comment by jmervine** [comment]
+1

**Comment by jdorfman** [comment]
Added in 1.0.0 docs
