### ISSUE TITLE
Apple product used in photos

### ISSUE THREAD

**Issue by adymitruk** [MaxCDN/shml#35]
Please remove Apple from something that is connected to the FSF.

**Comment by jmervine** [comment]
@adymitruk Would you mind clarifying? I think you're referring to the fact that the screenshots taken include a window header that appears to be Terminal.app. Is that correct?

cc @jdorfman

**Comment by jdorfman** [comment]
@jmervine he is referring to this: https://github.com/MaxCDN/shml/wiki/Official-Bash-Sticker-Giveaway

@adymitruk I will retake photos Monday (stickers are at the office) with non Apple products just for this case.

**Comment by jmervine** [comment]
Ah, yes. That makes more sense. :)

**Comment by adymitruk** [comment]
Perfect. Thanks!

**Comment by jdorfman** [comment]
@adymitruk done: https://github.com/MaxCDN/shml/wiki/Official-Bash-Sticker-Giveaway

Thanks for the heads up.  It was completely unintentional.
