### ISSUE TITLE
Controlling the Prompt with not-printable sequences.

### ISSUE THREAD

**Issue by drm343** [MaxCDN/shml#50]
My bash prompt work incorrect when use shml.
If prompt line too long, then text will overwrite the screen of current line and hard to see.

![2019-01-25 15-34-02](https://user-images.githubusercontent.com/1570047/51732797-5c890400-20ba-11e9-8cfc-48c48ba0eec9.png)

This bug appear because non-printable sequences. I fix this after add "\\[" and "\\]" in fgcolor and bgcolor.

![2019-01-25 15-34-17](https://user-images.githubusercontent.com/1570047/51733019-05cffa00-20bb-11e9-9ba0-552d2d4b7910.png)

Further reading:
* https://www.gnu.org/software/bash/manual/bashref.html#Controlling-the-Prompt

PR
#51

**Comment by jdorfman** [comment]
Thank you for the detailed issue. I commented on #51

**Comment by jmervine** [comment]
Okay this makes it much clearer. Thank you for the expanded explanation.
